config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  resources :audio_lessons
  resources :student_enrollments
  resources :video_lessons
  resources :lessons
  resources :courses
  resources :tutored_courses
  devise_for :students
  devise_for :tutors
  resources :students
  resources :user_profiles

  get 'home/student_home', as: :student_root
  get 'home/tutor_home'
  get '/tutor', to: 'home#tutor_home', as: :tutor_root
  get 'home/index'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :tutor
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_lesson.rb
class AudioLesson < ApplicationRecord
  belongs_to :lesson
  has_attached_file :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
  validates_presence_of :audio

  process_in_background :audio
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :tutored_courses

  def to_s
    name
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :tutored_course
  has_one :video_lesson, :dependent => :destroy
  has_one :audio_lesson, :dependent => :destroy
  has_many :questions
  validates_presence_of :title

  def to_s
    title
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :student
  belongs_to :lesson
  has_many :answers

  enum privacy: [ :Public, :Private ]

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_profile, optional: true
  has_many :student_enrollments

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/student_enrollment.rb
class StudentEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :tutored_course

  validates_uniqueness_of :tutored_course, message: 'You are already enrolled in this course'

  def to_s
    tutored_course.to_s
  end

  def tutor
    tutored_course.tutor
  end
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        #  :confirmable
  belongs_to :user_profile, optional: true
  has_many :tutored_courses

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/tutored_course.rb
class TutoredCourse < ApplicationRecord
  belongs_to :tutor
  belongs_to :course
  has_many :lessons, :dependent => :destroy
  has_many :student_enrollments

  def to_s
    course.to_s
  end

  def name_with_tutor
    "#{course.name} (with #{tutor})"
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one :tutor
  has_one :student
  validates_presence_of :first_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/video_lesson.rb
class VideoLesson < ApplicationRecord
  belongs_to :lesson

  has_attached_file :video, styles: {
    :medium => {
      :geometry => "640x480",
      :format => 'mp4'
    },
    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
    }, :processors => [:transcoder]
    validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
    validates_presence_of :video

    process_in_background :video
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tutor_home
    if !current_tutor.user_profile
      redirect_to new_user_profile_path
    end
    tutored_courses = current_tutor.tutored_courses.all
    if tutored_courses.size > 0
      @tutored_courses = tutored_courses
    end
  end

  def student_home
    if !current_student.user_profile
      redirect_to new_user_profile_path
    end
  end
end

app/controllers/video_lessons_controller.rb
class VideoLessonsController < ApplicationController
  before_action :set_video_lesson, only: [:show, :edit, :update, :destroy]

  # GET /video_lessons
  # GET /video_lessons.json
  def index
    @video_lessons = VideoLesson.all
  end

  # GET /video_lessons/1
  # GET /video_lessons/1.json
  def show
  end

  # GET /video_lessons/new
  def new
    @video_lesson = VideoLesson.new
    @video_lesson.lesson = Lesson.find(params[:lesson_id])
  end

  # GET /video_lessons/1/edit
  def edit
  end

  # POST /video_lessons
  # POST /video_lessons.json
  def create
    @video_lesson = VideoLesson.new(video_lesson_params)

    respond_to do |format|
      if @video_lesson.save
        format.html { redirect_to @video_lesson.lesson, notice: 'Video lesson was successfully created.' }
        format.json { render :show, status: :created, location: @video_lesson }
      else
        format.html { render :new }
        format.json { render json: @video_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_lessons/1
  # PATCH/PUT /video_lessons/1.json
  def update
    respond_to do |format|
      if @video_lesson.update(video_lesson_params)
        format.html { redirect_to @video_lesson, notice: 'Video lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_lesson }
      else
        format.html { render :edit }
        format.json { render json: @video_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_lessons/1
  # DELETE /video_lessons/1.json
  def destroy
    @video_lesson.destroy
    respond_to do |format|
      format.html { redirect_to video_lessons_url, notice: 'Video lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_lesson
      @video_lesson = VideoLesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_lesson_params
      params.require(:video_lesson).permit(:lesson_id, :video)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_lessons_helper.rb
module AudioLessonsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def questions_count(lesson)
    Question.where(lesson: lesson).count
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/video_lessons_helper.rb
module VideoLessonsHelper
end

app/views/video_lessons/_form.html.erb
<%= bootstrap_form_for(video_lesson, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>

<%= f.hidden_field :lesson_id %>
<%= f.file_field :video %>

<%= f.form_group do %>
<%= f.submit %>
<% end %>
<% end %>

app/views/video_lessons/edit.html.erb
<h1>Editing Video Lesson</h1>

<%= render 'form', video_lesson: @video_lesson %>

<%= link_to 'Show', @video_lesson %>
|
<%= link_to 'Back', lessons_path %>

app/views/video_lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Lessons</h1>

<table class="table">
  <thead>
    <tr>
      <th>Lesson</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_lessons.each do |video_lesson| %>
    <tr>
      <td><%= video_lesson.lesson %></td>
      <td><%= video_lesson.video %></td>
      <td><%= link_to 'Show', video_lesson %></td>
      <td><%= link_to 'Edit', edit_video_lesson_path(video_lesson) %></td>
      <td><%= link_to 'Destroy', video_lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Lesson', new_video_lesson_path %>

app/views/video_lessons/new.html.erb
<h1>New Video Lesson</h1>

<div id="video-capture">
  <h1><a href="//webrtc.github.io/samples/" title="WebRTC samples homepage">WebRTC samples</a> <span>MediaRecorder</span></h1>

  <p>This demo requires Firefox 29 or later, or Chrome 47 or later with <strong>Enable experimental Web Platform features</strong> enabled from chrome://flags.</p>

  <p>For more information see the MediaStream Recording API <a href="http://w3c.github.io/mediacapture-record/MediaRecorder.html" title="W3C MediaStream Recording API Editor's Draft">Editor's&nbsp;Draft</a>.</p>

  <video id="gum" autoplay muted></video>
  <video id="recorded" autoplay loop></video>

  <div>
    <button id="record" disabled>Start Recording</button>
    <button id="play" disabled>Play</button>
    <button id="download" disabled>Download</button>
  </div>

  <a href="https://github.com/webrtc/samples/tree/gh-pages/src/content/getusermedia/record" title="View source for this page on GitHub" id="viewSource">View source on GitHub</a>
</div>
<%#= render 'form', video_lesson: @video_lesson %>

<%= link_to 'Back', lessons_path %>

<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

app/views/video_lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lesson:</strong>
  <%= @video_lesson.lesson %>
</p>

<p>
  <strong>Video:</strong>
  <%= @video_lesson.video %>
</p>

<%= link_to 'Back', lessons_path %>