config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  resources :audio_lessons
  resources :student_enrollments
  resources :video_lessons
  resources :lessons
  resources :courses
  resources :tutored_courses
  devise_for :students
  devise_for :tutors
  resources :students
  resources :user_profiles

  get 'home/student_home', as: :student_root
  get 'home/tutor_home'
  get '/tutor', to: 'home#tutor_home', as: :tutor_root
  get 'home/index'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :tutor
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_lesson.rb
class AudioLesson < ApplicationRecord
  belongs_to :lesson
  has_attached_file :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
  validates_presence_of :audio

  process_in_background :audio
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :tutored_courses

  def to_s
    name
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :tutored_course
  has_one :video_lesson, :dependent => :destroy
  has_one :audio_lesson, :dependent => :destroy
  has_many :questions
  validates_presence_of :title

  def to_s
    title
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :student
  belongs_to :lesson
  has_many :answers

  enum privacy: [ :Public, :Private ]

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_profile, optional: true
  has_many :student_enrollments

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/student_enrollment.rb
class StudentEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :tutored_course

  validates_uniqueness_of :tutored_course, message: 'You are already enrolled in this course'

  def to_s
    tutored_course.to_s
  end

  def tutor
    tutored_course.tutor
  end
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        #  :confirmable
  belongs_to :user_profile, optional: true
  has_many :tutored_courses

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/tutored_course.rb
class TutoredCourse < ApplicationRecord
  belongs_to :tutor
  belongs_to :course
  has_many :lessons, :dependent => :destroy
  has_many :student_enrollments

  def to_s
    course.to_s
  end

  def name_with_tutor
    "#{course.name} (with #{tutor})"
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one :tutor
  has_one :student
  validates_presence_of :first_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/video_lesson.rb
class VideoLesson < ApplicationRecord
  belongs_to :lesson

  has_attached_file :video, styles: {
    :medium => {
      :geometry => "640x480",
      :format => 'mp4'
    },
    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
    }, :processors => [:transcoder]
    validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
    validates_presence_of :video

    process_in_background :video
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tutor_home
    if !current_tutor.user_profile
      redirect_to new_user_profile_path
    end
    tutored_courses = current_tutor.tutored_courses.all
    if tutored_courses.size > 0
      @tutored_courses = tutored_courses
    end
  end

  def student_home
    if !current_student.user_profile
      redirect_to new_user_profile_path
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    if current_tutor
      if params[:tutored_course] or session[:tutored_course_id]
        if params[:tutored_course]
          session[:tutored_course_id] = params[:tutored_course]
        end
        tutored_course = TutoredCourse.find(session[:tutored_course_id])
        @lessons = tutored_course.lessons
      else
        redirect_to tutored_courses_path
      end
    else
      @lessons = Lesson.all
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @tutored_course = TutoredCourse.find(session[:tutored_course_id])
  end

  # GET /lessons/1/edit
  def edit
    @tutored_course = TutoredCourse.find(session[:tutored_course_id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.tutored_course = TutoredCourse.find(session[:tutored_course_id])
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:tutored_course_id, :title, :summary)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audio_lessons_helper.rb
module AudioLessonsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def questions_count(lesson)
    Question.where(lesson: lesson).count
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/lessons/_form.html.erb
<%= bootstrap_form_for(lesson, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>

<%= f.static_control label: "Course" do %>
<%= @tutored_course %>
<% end %>
<%= f.text_field :title %>
<%= f.text_area :summary %>

<%= f.form_group do %>
<%= f.submit %>
<% end %>
<% end %>

app/views/lessons/edit.html.erb
<% content_for :section_nav do %>
<nav id="side-nav">
  <ul>
    <li id="nav-title">
      Lessons
    </li>
    <li>
      <%= link_to 'Back', lessons_path %>
    </li>
  </ul>
</nav>
<% end %>
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<% content_for :section_nav do %>
<nav id="side-nav">
  <ul>
    <li id="nav-title">
      Lessons
    </li>
    <% if current_tutor %>
    <li>
      <%= link_to 'New Lesson', new_lesson_path %>
    </li>
    <% end %>
  </ul>
</nav>
<% end %>

<h1><%= @lessons.first.tutored_course if @lessons and @lessons.first %>
  Lessons</h1>
<br/>

<% if @lessons %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
    <tr>
      <td><%= link_to "#{lesson.title.capitalize}", lesson_path(lesson) %></td>
      <td><%= lesson.summary %></td>
      <% if current_tutor %>
      <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/lessons/new.html.erb
<% content_for :section_nav do %>
<nav id="side-nav">
  <ul>
    <li id="nav-title">
      Lessons
    </li>
    <li>
      <%= link_to 'Back', lessons_path %>
    </li>
  </ul>
</nav>
<% end %>

<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

app/views/lessons/show.html.erb
<% content_for :section_nav do %>
<nav id="side-nav">
  <ul>
    <li id="nav-title">
      Lesson
    </li>
    <li>
      <%= link_to "Questions (#{questions_count @lesson})", questions_path(lesson_id: @lesson.id)%>
    </li>
    <% if current_tutor %>
    <li>
      <%= link_to 'Update Lesson', edit_lesson_path(@lesson) %>
    </li>
    <% end %>
    <li>
      <%= link_to 'Back', lessons_path %>
    </li>
  </ul>
</nav>
<% end %>

<p>
  <strong><%= @lesson.title %></strong>
  (<%= @lesson.tutored_course.course %>)
</p>

<% if @lesson.video_lesson %>
<video width="320" height="240" controls>
  <source src="<%= @lesson.video_lesson.video%>" type="video/mp4">
  Your browser does not support the video tag.
</video>
<% elsif @lesson.audio_lesson %>
<audio id="soundtrack" controls preload="auto">
  <source src="<%= @lesson.audio_lesson.audio%>" type="audio/mp3">
</audio>
<% end %>

<p>
  <br/>
  <%= @lesson.summary %>
</p>
<% if current_tutor and !(@lesson.video_lesson) %>
<%= link_to 'Upload video', new_video_lesson_path(lesson_id: @lesson.id ) %>
<% end %>
<% if current_tutor and !(@lesson.audio_lesson) %>
<%= link_to 'Upload Audio', new_audio_lesson_path(lesson_id: @lesson.id ) %>
<% end %>
</ul>