config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:create, :edit, :update, :destroy]
  end
  resources :audio_lessons
  resources :student_enrollments
  resources :video_lessons
  resources :lessons
  resources :courses
  resources :tutored_courses
  devise_for :students
  devise_for :tutors
  resources :students
  resources :user_profiles

  get 'home/student_home', as: :student_root
  get 'home/tutor_home'
  get '/tutor', to: 'home#tutor_home', as: :tutor_root
  get 'home/index'

  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :tutor
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio_lesson.rb
class AudioLesson < ApplicationRecord
  belongs_to :lesson
  has_attached_file :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
  validates_presence_of :audio

  process_in_background :audio
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :tutored_courses

  def to_s
    name
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :tutored_course
  has_one :video_lesson, :dependent => :destroy
  has_one :audio_lesson, :dependent => :destroy
  has_many :questions
  validates_presence_of :title

  def to_s
    title
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :student
  belongs_to :lesson
  has_many :answers

  enum privacy: [ :Public, :Private ]

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_profile, optional: true
  has_many :student_enrollments

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/student_enrollment.rb
class StudentEnrollment < ApplicationRecord
  belongs_to :student
  belongs_to :tutored_course

  validates_uniqueness_of :tutored_course, message: 'You are already enrolled in this course'

  def to_s
    tutored_course.to_s
  end

  def tutor
    tutored_course.tutor
  end
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        #  :confirmable
  belongs_to :user_profile, optional: true
  has_many :tutored_courses

  def to_s
    user_profile.full_name unless !user_profile
  end
end

app/models/tutored_course.rb
class TutoredCourse < ApplicationRecord
  belongs_to :tutor
  belongs_to :course
  has_many :lessons, :dependent => :destroy
  has_many :student_enrollments

  def to_s
    course.to_s
  end

  def name_with_tutor
    "#{course.name} (with #{tutor})"
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_one :tutor
  has_one :student
  validates_presence_of :first_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/video_lesson.rb
class VideoLesson < ApplicationRecord
  belongs_to :lesson

  has_attached_file :video, styles: {
    :medium => {
      :geometry => "640x480",
      :format => 'mp4'
    },
    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
    }, :processors => [:transcoder]
    validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/
    validates_presence_of :video

    process_in_background :video
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def tutor_home
    if !current_tutor.user_profile
      redirect_to new_user_profile_path
    end
    tutored_courses = current_tutor.tutored_courses.all
    if tutored_courses.size > 0
      @tutored_courses = tutored_courses
    end
  end

  def student_home
    if !current_student.user_profile
      redirect_to new_user_profile_path
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def questions_count(lesson)
    Question.where(lesson: lesson).count
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Education Provider</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">My Education Provider</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if !current_student and !current_tutor %>
            <li>
              <%= link_to 'Student', student_root_path %>
            </li>
            <li>
              <%= link_to 'Tutor', tutor_root_path %>
            </li>
            <% elsif current_tutor  %>
            <li><%= link_to 'Home', tutor_root_path %></li>
            <li><%= link_to 'Courses', tutored_courses_path %></li>
            <% elsif current_student %>
            <li><%= link_to 'Home', student_root_path %></li>
            <li>
              <%= link_to 'Courses', student_enrollments_path %>
            </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_student %>
              <%= link_to "Logout Student", destroy_student_session_path, method: :delete %>
              <% elsif current_tutor %>
              <%= link_to "Logout Tutor", destroy_tutor_session_path, method: :delete %>
              <% end %>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <main class="row">
        <div class="col-sm-3">

          <%= yield :section_nav %>

        </div>
        <div class="col-sm-9">
          <% flash.each do |name, msg| %>
          <div id="flash" class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss='alert'>&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
          <% end %>
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>